apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-portal-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-portal-backend
  template:
    metadata:
      labels:
        app: patient-portal-backend
    spec:
      containers:
        - name: backend
          image: patient-portal-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: SALESFORCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: salesforce-credentials
                  key: username
            - name: SALESFORCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: salesforce-credentials
                  key: password
            - name: SALESFORCE_SECURITY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: salesforce-credentials
                  key: security_token
