name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build & Push Backend Image
        run: docker build -t patient-portal-backend ./patient-portal-backend

      - name: Build & Push Frontend Image
        run: docker build -t patient-portal-frontend ./patient-portal-frontend

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
